name: Pouria.drd Website CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [22.x]

        env:
            EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
            EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
            EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
            EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
            EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
            DEFAULT_ADMINS_EMAILS: ${{ secrets.DEFAULT_ADMINS_EMAILS }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Navigate to Project Directory
              run: cd /home/pouria/actions-runner/_work/pouria.drd/pouria.drd

            - name: Install Project Dependencies
              run: npm install

            - name: Build the Project
              run: npm run build

            - name: Restart Application using PM2
              run: pm2 restart pouria.drd
